### ISSUE TITLE
这里bottom 重复声明了.  

### ISSUE THREAD

**Issue by zhang6321615** [icechao/kline#2]
https://github.com/icechao/kline/blob/9474333ea4229f2109dd8de20c1035faced7327b/klinelib/src/main/java/com/icechao/klinelib/draw/VolumeDraw.java#L95

**Comment by icechao** [comment]
@zhang6321615  已修改
https://github.com/icechao/kline/blob/9474333ea4229f2109dd8de20c1035faced7327b/klinelib/src/main/java/com/icechao/klinelib/draw/VolumeDraw.java#L95

**Comment by icechao** [comment]
update
