### ISSUE TITLE
MA5 MA10  MA30所在表格高度太高

### ISSUE THREAD

**Issue by zhuoshirong** [icechao/kline#6]
顶部 MA5   MA10  MA30所在表格高度太高，请问在哪里修改，火币的顶部MA5   MA10  MA30高度很低，然后5*5 的行列时日期会重叠在一起，点击日线能否增加显示对话框，现在是长按才能显示对话框

**Comment by icechao** [comment]
> 顶部 MA5 MA10 MA30所在表格高度太高，请问在哪里修改，火币的顶部MA5 MA10 MA30高度很低，然后5*5 的行列时日期会重叠在一起，点击日线能否增加显示对话框，现在是长按才能显示对话框

Ma5表格太高是指那三个指标的位置嘛?还是指文字大小
日期这个是重叠我这个可能要这种后面我加个开关吧~ 如果要不重叠坐标就要有一半出屏幕

点击显示的话会和滑动冲突的兄弟 ~   那你滑动准备怎么做,长按滑动嘛

如果着急你加下QQ群吧

**Comment by zhuoshirong** [comment]
我是更新了你代码，我是指第一行单元格高度：MA5 MA10 MA30 所在表格高度改小，我的意思是点击显示，长按也显示，滑动时就隐藏对话框，具体在哪里修改，麻烦了

**Comment by icechao** [comment]
你看下onLongPress的限制,和那个onScrollChange方法
修改下这里面的控制
